#!/bin/sh

ENABLED=yes
PROCS=snapclient
ARGS="-d --logsink file:/opt/var/log/snapclient.log --logfilter=*:info"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
