MusicFolder = '/opt/data/music'
DataFolder = '/opt/var/lib/navidrome'
ScanSchedule = "@every 1m"
LogLevel = "debug"
EnableLogRedacting = true
Port = "4533"
Address = "0.0.0.0"
EnableTranscodingConfig = false
TranscodingCacheSize = "100MB"
ImageCacheSize = "100MB"
AutoImportPlaylists = true
PlaylistsPath = ".:**/**"
#BaseUrl = 
#UILoginBackgroundUrl = 
#UIWelcomeMessage = 
GATrackingID = "disabled"
DefaultTheme = "Dark"
EnableCoverAnimation = true
IgnoredArticles = "The El La Los Las Le Les Os As O A"
SearchFullString = false
RecentlyAddedByModTime = false
CoverArtPriority = "embedded, cover.*, folder.*, front.*"
CoverJpegQuality = "75"
EnableDownloads = true
SessionTimeout = "24h"
AuthRequestLimit = "5"
AuthWindowLength = "20s"
Scanner.Extractor = "taglib"
Scanner.GenreSeparators = ";/,"
#LastFM.Enabled = 
#LastFM.ApiKey = 
#LastFM.Secret = 
#LastFM.Language = "en"
#Spotify.ID = 
#Spotify.Secret = 
#ListenBrainz.Enabled = true
#EnableGravatar = false
#EnableExternalServices = true
#EnableFavourites = true
#EnableStarRating = true
#EnableUserEditing = true
#PasswordEncryptionKey = 
#ReverseProxyUserHeader = 
#ReverseProxyWhitelist = 
