#!/bin/sh

. /opt/etc/filebrowser/filebrowser.conf

ENABLED=yes
PROCS=filebrowser
ARGS="$OPTIONS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


. /opt/etc/init.d/rc.func
