#!/bin/sh

ENABLED=yes
PROCS=turnserver
ARGS="-o -c /opt/etc/turnserver/turnserver.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
