#!/bin/sh

ENABLED=yes
PROCS=outline-ss-server
ARGS="-config /opt/etc/outline-ss-server.yml"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
