#!/bin/sh

ENABLED=yes
PROCS=dnsproxy
ARGS="--config-path=/opt/etc/dnsproxy.yaml"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
