#!/bin/sh

ENABLED=yes
PROCS=AdGuardHome
ARGS="--work-dir /opt/etc/AdGuardHome --logfile /opt/var/log/AdGuardHome.log --pidfile /opt/var/run/adguardhome.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
