#!/bin/sh

ENABLED=yes
PROCS=cloudreve
ARGS="-c /opt/var/lib/cloudreve/conf.ini"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
