#!/bin/sh

ENABLED=yes
PROCS=nginx-ui
ARGS="--config /opt/etc/nginx-ui/app.ini"
PREARGS=""
DESC="WebUI for Nginx"
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
